daily_planner/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include("for_everything.urls"))
]

for_everything/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.TaskView.as_view(), name="most_page"),
    # path('accounts', include('allauth.urls')),
    path("create", views.AddTask.as_view(), name="add_task"),
    path("delete/<int:pk>", views.Delete.as_view(), name="delete_task"),
    path("completeness/<int:pk>", views.Completeness.as_view(), name="complete_task"),
    path("my_completeness/<int:pk>", views.MyCompleteness.as_view(), name="my_complete_task"),
    path("history", views.TaskHistory.as_view(), name="history_tasks"),
    path("profile", views.Profile.as_view(), name="user_profile"),
    path("new_blogs", views.BlogView.as_view(), name="new_blog"),
    path("review/<int:pk>", views.AddReview.as_view(), name="add_review"),
]

for_everything/models.py
from django.db import models


class Task(models.Model):
    IMPORTANCE = (
        ("1", "very importance"),
        ("2", "importance"),
        ("3", "it would be better"),
        ("4", "not very important"),
        ("5", "trifle")
    )

    name = models.CharField(max_length=100)
    goal = models.TextField(max_length=1000)
    date_create = models.DateTimeField(auto_now_add=True)
    date_end = models.DateTimeField()
    importance = models.CharField(choices=IMPORTANCE, default="1", max_length=100)
    active = models.BooleanField(default=True)
    completeness = models.BooleanField(default=False)
    my_completeness = models.BooleanField(default=False)


class Blogs(models.Model):
    name_user = models.CharField(max_length=50)
    name_blog = models.CharField(max_length=100)
    description = models.TextField(max_length=2000)
    date_create = models.DateTimeField(auto_now_add=True)


class Reviews(models.Model):
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=2500)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True,
    )
    blog = models.ForeignKey(Blogs, verbose_name="блог", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.blog}"

    class Meta:
        verbose_name = "Коментарий"
        verbose_name_plural = "Коментарии"

for_everything/forms.py
from django import forms
from django.contrib.admin import widgets
from .models import Task, Blogs, Reviews


class TaskForm(forms.ModelForm):
    date_end = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime())

    class Meta:
        model = Task
        # fields = []
        exclude = ["active", "completeness"]
        widgets = {
            'goal': forms.Textarea(attrs={'class': 'my_goal_class'}),
        }


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blogs
        fields = ["name_blog", "description"]


class BlogReview(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ["text"]

for_everything/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Task, Blogs, Reviews
from .forms import TaskForm, BlogForm, BlogReview
from allauth.account.forms import LoginForm, SignupForm


def profile_count(tasks):
    tasks_count = tasks.count()
    my_completeness_tasks = tasks.filter(active=False, my_completeness=True, completeness=False).count()
    success_rate = my_completeness_tasks * 100 / 1
    success_rate1 = round(success_rate)
    return success_rate1


class TaskView(View):
    """Вывод задач"""
    def get(self, requests):
        tasks = Task.objects.all()
        task = tasks.filter(active=True, completeness=False)
        complete_task = Task.objects.filter(active=False, completeness=True).order_by()[:5]
        form = TaskForm()
        blogs = Blogs.objects.all()
        success_rate1 = profile_count(tasks)

        allauth_login = LoginForm(requests.POST or None)
        allauth_signup = SignupForm(requests.POST or None)

        return render(requests, "Task_list/base.html", {"Blogs_list": blogs, "Task_list": task, "complete_tasks": complete_task,
        "form": form, "success_rate1": success_rate1, "allauth_login": allauth_login, "allauth_signup": allauth_signup})


class BlogsView(View):
    def get(self, request):
        pass


class AddTask(View):
    def post(self, requests):
        form = TaskForm(requests.POST)
        if form.is_valid():
            form.save()
        return redirect("/")


class Delete(View):
    def post(self, requests, pk):
        task = Task.objects.get(id=pk)
        task.delete()

        return HttpResponse(status=200), redirect("/")


class MyCompleteness(View):
    def post(self, requests, pk):
        task = Task.objects.get(id=pk)
        task.my_completeness = True
        task.active = False
        task.save()

        return redirect("/")


class Completeness(View):
    def post(self, requests, pk):
        task = Task.objects.get(id=pk)
        task.completeness = True
        task.active = False
        task.save()

        return redirect("/")


class TaskHistory(View):
    def get(self, request):
        task = Task.objects.all()
        return render(request, "Task_list/history.html", {"Task_History": task})


class Profile(View):
    def get(self, request):
        tasks = Task.objects.all()
        success_rate1 = profile_count(tasks)
        return render(request, "Task_list/profile.html", {"success_rate1": success_rate1})


class BlogView(View):
    def get(self, request):
        return render(request, "Task_list/blog_create.html")

    def post(self, request):
        form = BlogForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.name_user = request.user.username
            form.save()
        return redirect("/")


class AddReview(View):
    def post(self, request, pk):
        form = BlogReview(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.blog_id = pk
            form.save()
        return redirect("/")

templates/Task_list/account/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

templates/Task_list/account/email.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "E-mail Addresses" %}{% endblock %}

{% block content %}
    <h1>{% trans "E-mail Addresses" %}</h1>
{% if user.emailaddress_set.all %}
<p>{% trans 'The following e-mail addresses are associated with your account:' %}</p>

<form action="{% url 'account_email' %}" class="email_list" method="post">
{% csrf_token %}
<fieldset class="blockLabels">

  {% for emailaddress in user.emailaddress_set.all %}
<div class="ctrlHolder">
      <label for="email_radio_{{forloop.counter}}" class="{% if emailaddress.primary %}primary_email{%endif%}">

      <input id="email_radio_{{forloop.counter}}" type="radio" name="email" {% if emailaddress.primary or user.emailaddress_set.count == 1 %}checked="checked"{%endif %} value="{{emailaddress.email}}"/>

{{ emailaddress.email }}
    {% if emailaddress.verified %}
    <span class="verified">{% trans "Verified" %}</span>
    {% else %}
    <span class="unverified">{% trans "Unverified" %}</span>
    {% endif %}
      {% if emailaddress.primary %}<span class="primary">{% trans "Primary" %}</span>{% endif %}
</label>
</div>
  {% endfor %}

<div class="buttonHolder">
      <button class="secondaryAction" type="submit" name="action_primary" >{% trans 'Make Primary' %}</button>
      <button class="secondaryAction" type="submit" name="action_send" >{% trans 'Re-send Verification' %}</button>
      <button class="primaryAction" type="submit" name="action_remove" >{% trans 'Remove' %}</button>
</div>

</fieldset>
</form>

{% else %}
<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc." %}</p>

{% endif %}

  {% if can_add_email %}
    <h2>{% trans "Add E-mail Address" %}</h2>

    <form method="post" action="{% url 'account_email' %}" class="add_email">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="action_add" type="submit">{% trans "Add E-mail" %}</button>
    </form>
  {% endif %}

{% endblock %}


{% block extra_body %}
<script type="text/javascript">
(function() {
  var message = "{% trans 'Do you really want to remove the selected e-mail address?' %}";
  var actions = document.getElementsByName('action_remove');
  if (actions.length) {
    actions[0].addEventListener("click", function(e) {
      if (! confirm(message)) {
        e.preventDefault();
      }
    });
  }
})();
</script>
{% endblock %}

templates/Task_list/account/email_confirm.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block content %}
<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

templates/Task_list/account/login.html
{% extends "base.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

<h1>{% trans "Sign In" %}</h1>

{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<p>{% blocktrans with site.name as site_name %}Please sign in with one
of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

<div class="socialaccount_ballot">

  <ul class="socialaccount_providers">
    {% include "socialaccount/snippets/provider_list.html" with process="login" %}
  </ul>

  <div class="login-or">{% trans 'or' %}</div>

</div>

{% include "socialaccount/snippets/login_extra.html" %}

{% else %}
<p>{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endif %}

<form class="login" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
  <button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
</form>

{% endblock %}

templates/Task_list/account/logout.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Out" %}</h1>

<p>{% trans 'Are you sure you want to sign out?' %}</p>

<form method="post" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit">{% trans 'Sign Out' %}</button>
</form>


{% endblock %}

templates/Task_list/account/password_change.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>

    <form method="POST" action="{% url 'account_change_password' %}" class="password_change">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="action">{% trans "Change Password" %}</button>
        <a href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
    </form>
{% endblock %}

templates/Task_list/account/password_reset.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'account_reset_password' %}" class="password_reset">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Reset My Password' %}" />
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>
{% endblock %}

templates/Task_list/account/password_reset_done.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}
    <h1>{% trans "Password Reset" %}</h1>
    
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}
    
    <p>{% blocktrans %}We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>
{% endblock %}

templates/Task_list/account/password_reset_from_key.html
{% extends "account/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% if token_fail %}{% trans "Bad Token" %}{% else %}{% trans "Change Password" %}{% endif %}</h1>

    {% if token_fail %}
        {% url 'account_reset_password' as passwd_reset_url %}
        <p>{% blocktrans %}The password reset link was invalid, possibly because it has already been used.  Please request a <a href="{{ passwd_reset_url }}">new password reset</a>.{% endblocktrans %}</p>
    {% else %}
        {% if form %}
            <form method="POST" action="{{ action_url }}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" name="action" value="{% trans 'change password' %}"/>
            </form>
        {% else %}
            <p>{% trans 'Your password is now changed.' %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

templates/Task_list/account/password_reset_from_key_done.html
{% extends "account/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>
    <p>{% trans 'Your password is now changed.' %}</p>
{% endblock %}

templates/Task_list/account/password_set.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Set Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Set Password" %}</h1>

    <form method="POST" action="{% url 'account_set_password' %}" class="password_set">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="action" value="{% trans 'Set Password' %}"/>
    </form>
{% endblock %}

templates/Task_list/account/signup.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Up" %}</h1>

<p>{% blocktrans %}Already have an account? Then please <a href="{{ login_url }}">sign in</a>.{% endblocktrans %}</p>

<form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
  {% csrf_token %}
  {{ form.as_p }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <button type="submit">{% trans "Sign Up" %} &raquo;</button>
</form>

{% endblock %}

templates/Task_list/account/snippets/already_logged_in.html
{% load i18n %}
{% load account %}

{% user_display user as user_display %}
<p><strong>{% trans "Note" %}:</strong> {% blocktrans %}you are already logged in as {{ user_display }}.{% endblocktrans %}</p>

templates/Task_list/account/verification_sent.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Verify Your E-mail Address" %}{% endblock %}

{% block content %}
    <h1>{% trans "Verify Your E-mail Address" %}</h1>

    <p>{% blocktrans %}We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>

{% endblock %}

templates/Task_list/account/verified_email_required.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Verify Your E-mail Address" %}{% endblock %}

{% block content %}
<h1>{% trans "Verify Your E-mail Address" %}</h1>

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This part of the site requires us to verify that
you are who you claim to be. For this purpose, we require that you
verify ownership of your e-mail address. {% endblocktrans %}</p>

<p>{% blocktrans %}We have sent an e-mail to you for
verification. Please click on the link inside this e-mail. Please
contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>

<p>{% blocktrans %}<strong>Note:</strong> you can still <a href="{{ email_url }}">change your e-mail address</a>.{% endblocktrans %}</p>


{% endblock %}

templates/Task_list/base.html
<!DOCTYPE html>
{% load static %}
{% load account %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;1,100&display=swap" rel="stylesheet">
</head>
<body>

<header>
    <ul class="mnu_top">
        <li><a class="history_form1" href="{% url 'history_tasks' %}">История</a></li>
        <li style="font-size: 25px;"><a href="#form_send" class="open_form">Создать задачу</a></li>
        <li><a href="{% url 'new_blog' %}">Создать блог</a></li>
    </ul>
    <div class="btns">
        {% csrf_token %}
        {% if user.is_authenticated %}
            <a href="{% url 'user_profile' %}"><span class="username">Вход выполнен как: {{ user.username }}</span></a>
            <a href="{% url 'account_logout'%}">Выйти</a>
        {% else %}
            <a class="primaryAction" href="{% url 'account_login' %}" type="submit">Войти</a>
            <a href="{% url 'account_signup' %}">Регистрация</a>
        {% endif %}
    </div>
</header>

{% if Task_list %}
{% for task in Task_list %}
<div class="all_tasks" id="all_t">
    <div id="task_name" class="task_name">
        {{ task.name }}
    </div>
    <div id="task_goal" class="task_goal">
        {{ task.goal }}
    </div>
    <div id="date" class="task_date_end">
        {{ task.date_end }}
    </div> - <span id="time_{{task.id}}" class="badge badge-success mr-3 p-3">yahoo!</span>
    <p id="{{task.id}}" class="test_p">{{ task.date_end|date:'c' }}</p>
    <form action="{% url 'delete_task' task.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
    <form action="{% url 'my_complete_task' task.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Complete</button>
    </form>
</div>


<script>
    function getTimeRemaining(endtime) {
        var t = Date.parse(endtime) - Date.parse(new Date())
        var seconds = Math.floor((t / 1000) % 60);
        var minutes = Math.floor((t / 1000 / 60) % 60);
        var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
        var days = Math.floor(t / (1000 * 60 * 60 * 24));
        return {
            total: t,
            days: days,
            hours: hours,
            minutes: minutes,
            seconds: seconds
        };
    }

    function initializeClock(id, pk, later) {
        var clock = document.getElementById(id);

        function updateClock() {
            var t = getTimeRemaining(later);

            if (t.total <= 0) {
                clearInterval(timeinterval);
                //alert("Task end")
                end_task(pk)
            }

            clock.innerHTML =
                `D ${("0" + t.days).slice(-2)} : H ${("0" + t.hours).slice(-2)} : M ${("0" + t.minutes).slice(-2)}
                : S ${("0" + t.seconds).slice(-2)}`;
        }
        updateClock();
        var timeinterval = setInterval(updateClock, 1000);
    }

    function start() {
        let t_p = document.querySelectorAll(".test_p");
        for (let i of t_p) {
            let deadline = new Date(Date.parse(i.innerHTML));
            console.log("deadline", deadline)
            initializeClock("time_" + i.id, i.id, deadline);
        }
    }

    function end_task(id) {
        let csrftoken = Cookies.get('csrftoken');
        let data = {
            pk: id,
        };
        fetch("http://127.0.0.1:8000/completeness/"+id, {
            method: 'POST',
            headers: {
                'Accept': 'application/json, text/plain, */*',
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest',
                "X-CSRFToken": csrftoken
                //'Content-Type': 'application/x-www-form-urlencoded',
            },
           // body: JSON.stringify(data),
        })
        .then(response => {
            if (response.status === 200) {
                alert("Task end server");
            }
        })
    }


    start()


</script>

{% endfor %}
{% endif %}

<div id="form_send" class="form_send">
    <div class="form_send_body">
        <div class="form_send_content">
            <a href="#" class="form_send_close">X</a>
            <form action="{% url 'add_task' %}" method="post" class="mt-4">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Добавить">
            </form>
        </div>
    </div>
</div>

<div id="end_tasks" class="end_tasks">
    <div id="end_content" class="end_content">
        {% for task in complete_tasks %}
        <br>
        {{ task.name }}
        <br>
        {{ task.goal }}
        <br>
        {% endfor %}
        <br>
    </div>
</div>

<div class="Success_Rate">
    {{success_rate1}} % успеваемость
</div>

{% for blogs in Blogs_list %}
<div class="Blog_View">
    <div class="description"></div>
        {{ blogs.date_create }}
    </div>
    <div class="Bloks_for_Blogs">
        <div class="name_user">
            {{ blogs.name_user }}
        </div>
        <div class="description"></div>
            {{ blogs.description }}
        </div>
    </div>
    <div class="AddReview">
        <form method="post" action="{% url 'add_review' blogs.id %}" class="mt-4">
            {% csrf_token %}
            <div class="description">
                <h4>Содержание</h4>
                <textarea id="new_blog" name="text" class="new_blogs"></textarea>
            </div>
            <div class="button">
                <button type="submit">Опубликовать</button>
            </div>
        </form>
    </div>
    {% for review in blogs.reviews_set.all %}
    <div class="ViewReview">
        <div class="name_author">
            {{ blogs.name_user }}
        </div>
        <div class="text">
            {{ review.text }}
        </div>
    </div>
    {% endfor %}
</div>
{% endfor %}

</body>
</html>

templates/Task_list/blog_create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'blog_create.css' %}" rel="stylesheet">
    <title>New Blog</title>
</head>
<body>
<header>
    <ul class="mnu_top">
        <li><a class="history_form1" href="{% url 'history_tasks' %}">История</a></li>
        <li style="font-size: 25px;"><a href="#form_send" class="open_form">Создать задачу</a></li>
        <li><a href="{% url 'most_page' %}">Вернуться на главную</a></li>
    </ul>
    <div class="btns">
        {% csrf_token %}
        {% if user.is_authenticated %}
            <a href="{% url 'user_profile' %}"><span class="username">Вход выполнен как: {{ user.username }}</span></a>
            <a href="{% url 'account_logout'%}">Выйти</a>
        {% else %}
            <a class="primaryAction" href="{% url 'account_login' %}" type="submit">Войти</a>
            <a href="{% url 'account_signup' %}">Регистрация</a>
        {% endif %}
    </div>
</header>

<div class="form_for_blog">
    <form action="" method="post" class="blog_send">
        {% csrf_token %}
        <div class="items">
            <h1 class="title_form">Новый блог</h1>
            <div class="name">
                <h4>Заголовок</h4>
                <input id="name_blog" type="text" name="name_blog">
            </div>
            <div class="description">
                <h4>Содержание</h4>
                <textarea id="new_blog" type="text" name="description" class="new_blogs"></textarea>
            </div>
        <div class="button">
            <button type="submit">Опубликовать</button>
        </div>
        </div>
    </form>
</div>

</body>
</html>

templates/Task_list/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks history</title>
</head>
<body>
{% for task in Task_History %}
<br>
{{ task.name }}
<br>
{{ task.goal }}
<br>
{{ task.date_end }}
<br>
{% endfor %}
<br>
</body>
</html>

templates/Task_list/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'profile.css' %}" rel="stylesheet">
    <title>{{ user.username }}</title>
</head>
<body>
<header>
    <ul class="mnu_top">
        <li><a class="history_form1" href="{% url 'history_tasks' %}">История</a></li>
        <li style="font-size: 25px;"><a href="#form_send" class="open_form">Создать задачу</a></li>
        <li><a href="{% url 'most_page' %}">Вернуться на главную</a></li>
    </ul>
    <div class="btns">
        {% csrf_token %}
        {% if user.is_authenticated %}
            <a href="{% url 'user_profile' %}"><span class="username">Вход выполнен как: {{ user.username }}</span></a>
            <a href="{% url 'account_logout'%}">Выйти</a>
        {% else %}
            <a class="primaryAction" href="{% url 'account_login' %}" type="submit">Войти</a>
            <a href="{% url 'account_signup' %}">Регистрация</a>
        {% endif %}
    </div>
</header>
{{ success_rate1 }} % успеваемость
</body>
</html>